### ISSUE TITLE
ImportError: No module named viper.common.abstracts

### ISSUE THREAD

**Issue by sha8e** [malice-plugins/pdf#1]
Hello,

Are you sure this docker works?

I get this error:
```
ImportError: No module named viper.common.abstracts
  File "/bin/pdfscan", line 10, in <module>
    from viper.common.abstracts import Module
```

Thank you for your help.

**Comment by blacktop** [comment]
Ah no @sha8e I apologize the 4 greatest malice plugins don't work:

- pdf  
- office  
- exe  
- javascript  

I try and mark the non-working plugins with `(WIP)` for work-in-progress and I have them disabled in `malice` so they don't try to run.

I have a lot of ideas on how they should work, but am distracted with trying to re-write the main malice engine here: https://github.com/maliceio/engine as well as trying to solidify how plugins will work for others to easily contribute them as well.

The main issue with those powerful core plugins is how to safely run them and then take a file and then output JSON from it as well as implementing a way to `pipe` them together so when a PDF has embedded Javascript to then pass that to the `javascript` plugin and keep track of where it came from and keep it all in sync and lossless.

I wil hopefully be able to finish these plugins soon and thank you for your interest in malice and it's plugins

**Comment by sha8e** [comment]
Thank you blacktop for your response and all the fantastic work you're doing.

I will wait until all is done, and then use malice again.

Wish you good luck.

**Comment by vvhappyguy** [comment]
Hello, I want to say that malice plugins are so good. I try a lot of part of them.
But I have mistake, which @sha8e had. Are they working now?
I really want to use malice/pdf and malice/office. I have already used other malice plugins.
Thank you for your help.

**Comment by blacktop** [comment]
plugin is working now 😉 

I am presenting malice at Blackhat Arsenal and will hopefully be finishing the other plugins soon as well as the re-write and UI overhaul.

😫 

kthxbye
